import type { ColorPalette } from './types';

export const stylePalettes: Record<string, ColorPalette[]> = {
  Scandinavian: [
    { name: 'Warm White', hex: '#F5F0E8' },
    { name: 'Soft Greige', hex: '#D8CFC4' },
    { name: 'Light Oak', hex: '#C4A882' },
    { name: 'Stone Grey', hex: '#B5B0A8' },
    { name: 'Muted Sage', hex: '#A8B5A0' },
    { name: 'Frost White', hex: '#EDEAE4' },
  ],
  Japandi: [
    { name: 'Warm Beige', hex: '#D4C5B0' },
    { name: 'Clay', hex: '#B89B7C' },
    { name: 'Muted Olive', hex: '#8A8B70' },
    { name: 'Light Ash', hex: '#C8C2B6' },
    { name: 'Cream', hex: '#E8DFD0' },
    { name: 'Soft Charcoal', hex: '#5C5854' },
  ],
  Minimalist: [
    { name: 'Pure White', hex: '#F8F6F3' },
    { name: 'Light Grey', hex: '#D1D0CE' },
    { name: 'Cloud Grey', hex: '#BFC1C4' },
    { name: 'Soft Taupe', hex: '#A39080' },
    { name: 'Misty White', hex: '#E5E7E9' },
    { name: 'Pale Stone', hex: '#CCC7BF' },
  ],
  Industrial: [
    { name: 'Concrete', hex: '#A8A6A1' },
    { name: 'Graphite', hex: '#4A4A48' },
    { name: 'Steel Blue', hex: '#6B7B8C' },
    { name: 'Ash Grey', hex: '#9B9B96' },
    { name: 'Walnut', hex: '#6B5344' },
    { name: 'Charcoal', hex: '#3D3D3B' },
  ],
  Bohemian: [
    { name: 'Terracotta', hex: '#B5704A' },
    { name: 'Olive', hex: '#7A7B5A' },
    { name: 'Camel', hex: '#B89B6E' },
    { name: 'Sand', hex: '#C9B89A' },
    { name: 'Clay', hex: '#A67B5B' },
    { name: 'Muted Rust', hex: '#9C5E3E' },
  ],
  Coastal: [
    { name: 'Sea Mist', hex: '#C5D5D8' },
    { name: 'Driftwood', hex: '#A89882' },
    { name: 'Soft Aqua', hex: '#A8C4C8' },
    { name: 'Sandy White', hex: '#E8DFD0' },
    { name: 'Ocean Grey', hex: '#7B8E94' },
    { name: 'Shell White', hex: '#F0EBE4' },
  ],
  'Modern Luxury': [
    { name: 'Champagne', hex: '#D4C4A8' },
    { name: 'Deep Mocha', hex: '#5C4438' },
    { name: 'Pearl Grey', hex: '#C0BBB5' },
    { name: 'Soft Black', hex: '#3A3A38' },
    { name: 'Warm Bronze', hex: '#8A7048' },
    { name: 'Ivory', hex: '#EDE6D8' },
  ],
  Farmhouse: [
    { name: 'Barn White', hex: '#F0EBE0' },
    { name: 'Aged Wood', hex: '#9C7E5E' },
    { name: 'Sage Green', hex: '#9CAA8C' },
    { name: 'Dusty Blue', hex: '#9AAEB8' },
    { name: 'Warm Linen', hex: '#D8CCB8' },
    { name: 'Soft Charcoal', hex: '#5C5854' },
  ],
  Traditional: [
    { name: 'Elegant Cream', hex: '#E0D5C2' },
    { name: 'Deep Navy', hex: '#3D4A5C' },
    { name: 'Warm Taupe', hex: '#A39080' },
    { name: 'Forest Green', hex: '#4A5D4A' },
    { name: 'Burgundy', hex: '#6B3D3D' },
    { name: 'Soft Gold', hex: '#C4A868' },
  ],
  'Mid Century': [
    { name: 'Mustard', hex: '#B89B3E' },
    { name: 'Teal', hex: '#4A7B7B' },
    { name: 'Walnut Brown', hex: '#6B4E3A' },
    { name: 'Olive Green', hex: '#6B7A4A' },
    { name: 'Burnt Orange', hex: '#A8623A' },
    { name: 'Soft Cream', hex: '#E8DFD0' },
  ],
  Mediterranean: [
    { name: 'Terracotta', hex: '#B5704A' },
    { name: 'Azure Blue', hex: '#4A7B9C' },
    { name: 'Warm Sand', hex: '#C9B89A' },
    { name: 'Olive Green', hex: '#6B7A4A' },
    { name: 'Sun Washed White', hex: '#EDE6D8' },
    { name: 'Muted Coral', hex: '#B87A6E' },
  ],
  Contemporary: [
    { name: 'Cool White', hex: '#EDEBE8' },
    { name: 'Soft Grey', hex: '#C5C3C0' },
    { name: 'Warm Taupe', hex: '#A39080' },
    { name: 'Deep Charcoal', hex: '#3D3D3B' },
    { name: 'Muted Blue', hex: '#7B8E9C' },
    { name: 'Soft Stone', hex: '#CCC7BF' },
  ],
  'Art Deco': [
    { name: 'Black Pearl', hex: '#2A2A28' },
    { name: 'Antique Gold', hex: '#B89B4E' },
    { name: 'Deep Emerald', hex: '#2D5D4A' },
    { name: 'Cream Ivory', hex: '#E8DFD0' },
    { name: 'Burgundy', hex: '#6B3D3D' },
    { name: 'Soft Brass', hex: '#9C8048' },
  ],
  Rustic: [
    { name: 'Weathered Wood', hex: '#9C7E5E' },
    { name: 'Forest Green', hex: '#4A5D4A' },
    { name: 'Warm Stone', hex: '#B5A88E' },
    { name: 'Barn Red', hex: '#7B4A3D' },
    { name: 'Natural Linen', hex: '#D8CCB8' },
    { name: 'Deep Brown', hex: '#4A3A2E' },
  ],
  'French Country': [
    { name: 'Soft Lavender', hex: '#B5A8B8' },
    { name: 'Warm Cream', hex: '#E8DFD0' },
    { name: 'Muted Blue', hex: '#7B8E9C' },
    { name: 'Aged White', hex: '#EDE6D8' },
    { name: 'Soft Sage', hex: '#9CAA8C' },
    { name: 'Dusty Rose', hex: '#B89A92' },
  ],
  'Organic Modern': [
    { name: 'Warm Clay', hex: '#B89B7C' },
    { name: 'Soft Mushroom', hex: '#B5A89C' },
    { name: 'Natural Linen', hex: '#D8CCB8' },
    { name: 'Muted Olive', hex: '#8A8B70' },
    { name: 'Stone White', hex: '#EDEAE4' },
    { name: 'Soft Terracotta', hex: '#A67B5B' },
  ],
  'Wabi Sabi': [
    { name: 'Raw Plaster', hex: '#C5BFB5' },
    { name: 'Aged Paper', hex: '#DDD5C8' },
    { name: 'Muted Earth', hex: '#8A7B6A' },
    { name: 'Soft Stone', hex: '#CCC7BF' },
    { name: 'Weathered Grey', hex: '#9B9B96' },
    { name: 'Natural Hemp', hex: '#C9B89A' },
  ],
  'Hollywood Regency': [
    { name: 'Lacquer Black', hex: '#2A2A28' },
    { name: 'Champagne Gold', hex: '#C4A868' },
    { name: 'Pure Ivory', hex: '#EDE6D8' },
    { name: 'Deep Sapphire', hex: '#2A4A6B' },
    { name: 'Soft Pearl', hex: '#D8D0C4' },
    { name: 'Burgundy', hex: '#6B3D3D' },
  ],
};

export const allStyles = Object.keys(stylePalettes);
